export const APP_NAME = process.env.APP_NAME || "Trello - Task Manager"
export const APP_DESCRIPTION = process.env.APP_DESCRIPTION || "A Task Manager tool for team to collaborate and work with Tasks."
export const APP_VERSION = process.env.APP_VERSION || ""
export const APP_AUTHOR = process.env.APP_AUTHOR || ""
export const APP_AUTHOR_EMAIL = process.env.APP_AUTHOR_EMAIL || ""
export const APP_AUTHOR_URL = process.env.APP_AUTHOR_URL || ""
